# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
    
trigger: none

pr:
- master

resources:
  repositories:
    - repository: devops-project-samples
      type: github
      endpoint: silviuandrica
      name: silviuandrica/devops-project-samples
steps: 
  - checkout: self    
  - checkout: devops-project-samples
    persistCredentials: true   # this must be set to extract the GitHub token
  - bash: |
      export remote_url=$(git config remote.origin.url)
      export remote_auth=$(git config http.$remote_url.extraheader)
      export remote_auth_token=$(awk '{print $NF}' <<< $remote_auth)
      echo "##vso[task.setvariable variable=GITHUB_TOKEN;]$remote_auth_token"
      echo "GitHub token: $remote_auth_token"
      echo $SECRET_GITHUB_TOKEN
    workingDirectory: $(Build.SourcesDirectory)/devops-project-samples
    displayName: "Set GITHUB_TOKEN"

# extends:
#   template: base.yml
#   parameters:
#     stages:
#     - stage:
#       displayName: Build app
#       jobs:
#         - template: job.template.yml
#           parameters:
#             name: linux
#             pool:
#               vm: linux-latest
#     resultsPrefix: pipelines-javascript