# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  pipelines:
    - pipeline: upstream
      source: silviuandrica.pipelines-javascript
      trigger:
        branches:
          - master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo silviuandrica.pipelines-javascript