# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  runNumber: 20220627.3
resources:
  pipelines:
    - pipeline: upstream
      source: silviuandrica.pipelines-javascript
      branch: $(runNumber)
      trigger: true

  repositories:
    - repository: devops-project-samples
      type: github
      endpoint: silviuandrica
      name: silviuandrica/devops-project-samples

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build 
    jobs: 
      - job:
        steps:
        - checkout: self
        - checkout: devops-project-samples
        - script: echo downstream!
        - script: echo upstream pipeline name is $(resources.pipeline.upstream.pipelineName)
        - script: echo upstream pipeline id is $(resources.pipeline.upstream.pipelineID)
        - script: echo upstream pipeline run name is $(resources.pipeline.upstream.runName)
        - script: echo upstream pipeline runID is $(resources.pipeline.upstream.runID)
  - stage: deploy
    jobs:
      - deployment: deployJob
        environment: Local
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
                - script: echo Deploying